const {chromium}=require('playwright');
const errs=[];
(async()=>{
 const b=await chromium.launch();
 const p=await (await b.newContext({viewport:{width:780,height:520}})).newPage();
 p.on('pageerror',e=>errs.push('PAGEERROR '+(e.stack||e.message).split('\n').slice(0,3).join(' | ')));
 p.on('console',m=>{ if(m.type()==='error') errs.push('CONSOLE '+m.text().slice(0,200)); });
 await p.goto('http://127.0.0.1:4178/ff-iphone/index.html'); await p.waitForTimeout(1200);
 const t=async(name,fn)=>{ try{ const r=await p.evaluate(fn); console.log('✓',name,JSON.stringify(r).slice(0,320)); }catch(e){ console.log('✗',name,e.message.split('\n')[0]); errs.push('TEST '+name+': '+e.message.split('\n')[0]); } };
 await t('démarrage',()=>{FF.Game.boot(document.getElementById('game')); FF.Game.newGame(); FF.Game.noEnc=true; return FF.Game.state;});
 await t('fin intro',()=>{ FF.Wld.cut=null; FF.UI.dlg=null; FF.Wld.enter('aurelia',15,20,'down'); return FF.Wld.map.id;});
 await t('sauvegarde directe',()=>{ const ok=FF.Save.save('1'); return {ok, meta:FF.Save.meta('1'), raw: !!localStorage.getItem('q4c.save.1')};});
 await t('nom membres',()=>FF.S.order.map(i=>FF.S.members[i].n+'/'+FF.S.members[i].name));
 await t('aller au sanctuaire + entrer',()=>{ FF.Wld.enter('world',16,9,'up'); return {p:{x:FF.Wld.p.gx,y:FF.Wld.p.gy}, tile:FF.Wld.tileAt(FF.Wld.p.gx,FF.Wld.p.gy)};});
 await p.waitForTimeout(60);
 await t('entrée donjon via porte',()=>{ const d=(FF.Wld.map.ents||[]).find(e=>e.t==='door'&&String(e.to)==='sanctuaire_1'); if(!d) return 'porte absente'; FF.Wld.tryInteract(d,{},true); return {triggered:1};});
 await p.waitForTimeout(500);
 await t('dans le donjon',()=>({map:FF.Wld.map.id, rows:FF.Wld.map.rows.length, pos:{x:FF.Wld.p.gx,y:FF.Wld.p.gy}, sol:FF.Wld.tileAt(FF.Wld.p.gx,FF.Wld.p.gy)}));
 await t('escaliers suite',()=>{ const st=(FF.Wld.map.ents||[]).filter(e=>e.t==='stairs'||e.t==='stairsback'||e.t==='chest'||e.t==='save'||e.t==='bossgate').map(e=>e.t+'@'+e.x+','+e.y); return st;});
 await t('coffre forcé',()=>{ const e=(FF.Wld.map.ents||[]).find(x=>x.t==='chest'); if(!e) return 'aucun'; const before=JSON.stringify(FF.S.inv)+JSON.stringify(FF.S.gear)+FF.S.gils; FF.Wld.tryInteract(e,{},true); return {before:before.slice(0,60), after:(JSON.stringify(FF.S.inv)+JSON.stringify(FF.S.gear)).slice(0,60), msg:FF.UI.dlg?FF.UI.dlg.linesArr:''};});
 await t('cristal de sauvegarde',()=>{ FF.UI.crystal(); const m=FF.UI.menu; return m?Object.keys(m):'pas de menu';});
 await t('menu ouvert',()=>{ FF.UI.close(); FF.UI.openMenu(); const m=FF.UI.menu; return m?{kind:m.kind,items:m.L.items.map(i=>i.t)}:'!';});
 await t('magie hors combat',()=>{ FF.UI.close(); const m0=FF.S.members.arno; m0.gifted=['soin']; FF.P.recalc(m0); m0.mp=0; FF.UI.castField(m0, FF.D.SP.soin); return {mp:m0.mp, hp:FF.S.members.myrelle.hp|0};});
 await t('combat complet',async()=>{});
 await p.evaluate(()=>{ FF.UI.close(); FF.Game.battle({foes:['limule','chatsouris'],bg:'field',music:'battle',name:'Rencontre'}); });
 for(let i=0;i<80;i++){ const st=await p.evaluate(()=>{ if(!FF.Bat.st) return null; if(FF.Bat.st.mode==='cmd'){FF.In.force('a');} else if(FF.Bat.st.mode==='target'){FF.In.force('a');} else if(FF.Bat.st.showResult&&FF.Bat.st.mode==='win'){FF.In.force('a');} return {mode:FF.Bat.st.mode,turn:FF.Bat.st.turns,hp:FF.Bat.st.allies.map(a=>a.hp|0),foe:FF.Bat.st.foes.map(f=>f.hp|0)};}); if(!st){console.log('✓ combat terminé à l\'itération',i);break;} if(i%10===0) console.log('  état combat',i,JSON.stringify(st)); await p.waitForTimeout(180); }
 await t('après combat',()=>({state:FF.Game.state, gils:FF.S.gils, lvl:FF.S.order.map(i=>FF.S.members[i].lv), hp:FF.S.order.map(i=>FF.S.members[i].hp|0)}));
 await t('boss gate',()=>{ const g=(FF.Wld.map.ents||[]).find(e=>e.t==='bossgate'); if(!g) return 'pas de gate ici'; FF.Wld.tryInteract(g,{},true); return {state:FF.Game.state, mode:FF.Bat.st&&FF.Bat.st.mode, foes:FF.Bat.st&&FF.Bat.st.foes.map(f=>f.name)};});
 await t('dirigeable',()=>{ FF.S.set('ship'); FF.S.ship=1; FF.Wld.enter('world',30,10,'down'); const ok=FF.Wld.board(); return {mode:FF.Wld.mode, ok:!!ok};});
 await t('vol + atterrissage',()=>{ FF.Wld.land&&FF.Wld.land(); return FF.Wld.mode;});
 await t('retour ville + auberge',()=>{ FF.Wld.enter('aurelia',15,20,'down'); const inn=(FF.Wld.map.ents||[]).find(e=>e.t==='npc'&&e.inn); return inn?{found:1,price:inn.inn}:'auberge absente de la carte aurelia (normal: elle est dans l’intérieur)';});
 await t('chambre → repos',()=>{ FF.Wld.enter('aurelia-inn',2,4,'down'); S=FF.S; FF.S.allMembers().forEach(m=>{m.hp=1;m.mp=0;}); const bed=(FF.Wld.map.ents||[]).find(e=>e.t==='bed'||e.t==='npc'&&e.inn); if(!bed) return 'aucun lit'; FF.Wld.tryInteract(bed,{},true); FF.UI.close(); return {map:FF.Wld.map.id, beds:(FF.Wld.map.ents||[]).filter(e=>e.t==='bed').length};});
 await t('emploi / jobs',()=>{ FF.S.jobs.dark=1; FF.UI.jobMenu(FF.S.order[0]); const m=FF.UI.menu; if(!m) return '!'; const dark=m.L.items.find(i=>/Chevalier Noir/.test(i.t)); if(dark&&m.L.onSel) m.L.onSel(dark); return {job:FF.S.members.arno.job, pv:FF.S.members.arno.stats.pv};});
 await t('équipement',()=>{ FF.UI.close(); FF.S.add('plaque',1); const before=FF.S.members.arno.stats.def; FF.UI.equipMenu(FF.S.order[0]); const m=FF.UI.menu; const it=m.L&&m.L.items.find(i=>/Plaques|Armure de Plates/.test(i.t)); if(it&&m.L.onSel) m.L.onSel(it); return {def:FF.S.members.arno.stats.def, before, equipped:FF.S.members.arno.equip.armor};});
 await t('dialogue npc',()=>{ FF.UI.close(); FF.Wld.enter('aurelia',15,20,'down'); const n=(FF.Wld.map.ents||[]).find(e=>e.t==='npc'&&!e.hide); FF.Wld.talk(n); return FF.UI.dlg?FF.UI.dlg.linesArr:'aucun dialogue pour '+(n&&n.say);});
 await t('cristal → recharge',()=>{ FF.S.allMembers().forEach(m=>{m.hp=1;}); FF.UI.crystal(); const L=FF.UI.menu.L; L.onSel(L.items[0]); return {hp:FF.S.order.map(i=>FF.S.members[i].hp|0), pm:FF.S.order.map(i=>FF.S.members[i].mp|0)};});
 await t('chargement',()=>{ FF.S.allMembers().forEach(m=>{m.hp=1;}); const ok=FF.Save.load('1'); return {ok, hp:FF.S.order.map(i=>FF.S.members[i].hp|0)};});
 await p.waitForTimeout(400);
 await p.screenshot({path:'/home/user/shots/f-final.png'});
 console.log(errs.length? 'ERREURS:\n  '+errs.slice(0,20).join('\n  '):'AUCUNE ERREUR');
 await b.close(); process.exit(errs.length?1:0);
})();
