/* Tirs d'inspection (format au choix) -> /home/user/shots/x-*.png */
const { chromium } = require('playwright');
require('fs').mkdirSync('/home/user/shots', { recursive: true });
const vw = +(process.env.VW || 844), vh = +(process.env.VH || 390);
const DSF = +(process.env.DSF || 2);
(async () => {
  const br = await chromium.launch();
  const p = await br.newPage({ viewport: { width: vw, height: vh, isMobile: true, deviceScaleFactor: DSF } });
  const errs = [];
  p.on('pageerror', e => errs.push('PE ' + (e.stack || e.message).split('\n').slice(0, 2).join(' | ')));
  p.on('console', m => { if (m.type() === 'error') errs.push('CE ' + m.text().slice(0, 110)); });
  await p.goto('http://127.0.0.1:4178/ff-iphone/index.html', { waitUntil: 'load' });
  await p.waitForTimeout(400);
  const sh = (n) => p.screenshot({ path: '/home/user/shots/x-' + n + '.png' });
  await p.mouse.click(Math.round(vw / 2), Math.round(vh * .5));
  await p.waitForTimeout(1000);
  await p.evaluate(() => { FF.In.pressed = () => false; FF.In.tap = () => false; FF.In.consume = () => false; FF.In.hold = () => 0; });
  await sh('title');
  await p.evaluate(() => { FF.Game.state.screen = 'field'; FF.UI.openMenu('item'); });
  await p.waitForTimeout(160); await sh('item');
  await p.evaluate(() => { FF.UI.openMenu('party'); });
  await p.waitForTimeout(160); await sh('party');
  await p.evaluate(() => { FF.UI.openMenu('job'); });
  await p.waitForTimeout(160); await sh('job');
  await p.evaluate(() => { FF.UI.openMenu('config'); });
  await p.waitForTimeout(160); await sh('config');
  await p.evaluate(() => { FF.UI.close(); FF.Game.noEnc = true; FF.Bat.start({ foes: ['sable_vif', 'scarabee_de_sable'], onEnd: () => { } }); });
  await p.waitForTimeout(600); await sh('battle');
  await p.evaluate(() => { const st = FF.Bat.st; st.mode = 'sub'; st.sub = 'sp'; st.actor = st.allies.find(a => a.curMP > 0) || st.allies[0]; });
  await p.waitForTimeout(200); await p.evaluate(() => { FF.Bat.update(0.016); FF.Bat.draw(); }); await sh('mag');
  await p.evaluate(() => { const st = FF.Bat.st, m = FF.S.order.map(function(i){return FF.S.members[i]})[1]; FF.S.inv['potion'] = 4; FF.S.inv['ether'] = 2; FF.S.inv['phoenix'] = 1; st.mode = 'sub'; st.sub = 'it'; st.actor = m; });
  await p.waitForTimeout(200); await p.evaluate(() => { FF.Bat.update(0.016); FF.Bat.draw(); }); await sh('obj');
  await p.evaluate(() => { const st = FF.Bat.st; st.mode = 'cmd'; });
  await p.waitForTimeout(120); await sh('cmd');
  await p.evaluate(() => { const st = FF.Bat.st; st.mode = 'target'; st.tgtSide = 'allies'; st.pending = { kind: 'sp', id: 'soin' }; st.target = 1; st.actor = st.allies.find(a => a.curMP > 0) || st.allies[0]; });
  await p.waitForTimeout(220); await sh('cast');
  await p.evaluate(() => { try { FF.UI.dialog('Arno', ['Le désert est immense, et nos réserves minces comme du papier de riz. Que chacun compte ses potions avant la prochaine dune.']); FF.UI.update(0.016); FF.UI.draw(); } catch (e) { } });
  await p.waitForTimeout(150); await sh('dialog');
  console.log(JSON.stringify(errs));
  await br.close();
})();
